"""initial schema - companies, users, uploads, departments, suppliers,
raw_materials, products, production_runs, contractor_ledger_entries, expenses

Revision ID: 0001
Revises:
Create Date: Day 5

Written by hand against the SQLAlchemy models rather than autogenerated,
since there's no live Postgres connection available in this environment.
Before relying on this in a real run: install deps, point DATABASE_URL at
a real Postgres instance, then run:

    alembic revision --autogenerate -m "verify against 0001"

...and diff the result against this file to confirm they match. Autogenerate
should produce an empty migration if this file is accurate.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "companies",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("industry", sa.String(100), server_default="textile_apparel"),
        sa.Column("country", sa.String(100), nullable=True),
        sa.Column("currency", sa.String(10), server_default="PKR"),
        sa.Column("business_type", sa.String(100), nullable=True),
        sa.Column("fiscal_year_start_month", sa.Integer(), server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=True),
        sa.Column("role", sa.Enum(
            "ceo", "production_manager", "inventory_manager", "finance_manager", "sales_manager", "admin",
            name="userrole"), server_default="ceo"),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "uploads",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("original_filename", sa.String(500), nullable=False),
        sa.Column("stored_path", sa.String(1000), nullable=False),
        sa.Column("status", sa.Enum(
            "uploaded", "mapped", "validated", "imported", "failed", name="uploadstatus"),
            server_default="uploaded"),
        sa.Column("column_mapping", sa.JSON(), nullable=True),
        sa.Column("validation_issues", sa.JSON(), nullable=True),
        sa.Column("rows_imported", sa.Integer(), nullable=True),
        sa.Column("uploaded_by_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_uploads_company_id", "uploads", ["company_id"])

    op.create_table(
        "departments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("sequence_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true()),
        sa.Column("applies_to_stream", sa.String(20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_departments_company_id", "departments", ["company_id"])

    op.create_table(
        "suppliers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("contact_info", sa.String(500), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_suppliers_company_id", "suppliers", ["company_id"])

    op.create_table(
        "raw_materials",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("supplier_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("suppliers.id"), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("material_type", sa.String(100), nullable=True),
        sa.Column("unit", sa.String(20), nullable=False),
        sa.Column("last_known_unit_price", sa.Numeric(12, 2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_raw_materials_company_id", "raw_materials", ["company_id"])

    op.create_table(
        "products",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("cloth_type", sa.String(255), nullable=False),
        sa.Column("article_code", sa.String(100), nullable=True),
        sa.Column("cost_per_meter", sa.Numeric(12, 2), nullable=True),
        sa.Column("cloth_meters_per_piece", sa.Numeric(10, 3), nullable=True),
        sa.Column("cloth_cost_per_piece", sa.Numeric(12, 2), nullable=True),
        sa.Column("stitching_cost_per_piece", sa.Numeric(12, 2), nullable=True),
        sa.Column("embroidery_cost_per_piece", sa.Numeric(12, 2), nullable=True),
        sa.Column("washing_cost_per_piece", sa.Numeric(12, 2), nullable=True),
        sa.Column("total_cost_per_piece", sa.Numeric(12, 2), nullable=True),
        sa.Column("sale_price_per_piece", sa.Numeric(12, 2), nullable=True),
        sa.Column("profit_per_piece", sa.Numeric(12, 2), nullable=True),
        sa.Column("source", sa.String(20), server_default="verified"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_products_company_id", "products", ["company_id"])

    op.create_table(
        "production_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("products.id"), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("stream", sa.Enum("self_made", "cmt", "unspecified", name="productionstream"),
                   server_default="unspecified"),
        sa.Column("article_label", sa.String(100), nullable=True),
        sa.Column("quantity", sa.Numeric(12, 2), nullable=True),
        sa.Column("cost_total", sa.Numeric(14, 2), nullable=True),
        sa.Column("sale_price_piece", sa.Numeric(12, 2), nullable=True),
        sa.Column("revenue_total", sa.Numeric(14, 2), nullable=True),
        sa.Column("profit", sa.Numeric(14, 2), nullable=True),
        sa.Column("source_upload_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("uploads.id"), nullable=True),
        sa.Column("source_sheet", sa.String(100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_production_runs_company_id", "production_runs", ["company_id"])
    op.create_index("ix_production_runs_date", "production_runs", ["date"])

    op.create_table(
        "contractor_ledger_entries",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount_billed", sa.Numeric(14, 2), nullable=True),
        sa.Column("amount_paid", sa.Numeric(14, 2), nullable=True),
        sa.Column("running_balance", sa.Numeric(14, 2), nullable=True),
        sa.Column("source_upload_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("uploads.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_contractor_ledger_entries_company_id", "contractor_ledger_entries", ["company_id"])
    op.create_index("ix_contractor_ledger_entries_date", "contractor_ledger_entries", ["date"])

    op.create_table(
        "expenses",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(500), nullable=True),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("amount_received", sa.Numeric(14, 2), nullable=True),
        sa.Column("amount_used", sa.Numeric(14, 2), nullable=True),
        sa.Column("running_balance", sa.Numeric(14, 2), nullable=True),
        sa.Column("source_upload_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("uploads.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_expenses_company_id", "expenses", ["company_id"])
    op.create_index("ix_expenses_date", "expenses", ["date"])


def downgrade():
    op.drop_table("expenses")
    op.drop_table("contractor_ledger_entries")
    op.drop_table("production_runs")
    op.drop_table("products")
    op.drop_table("raw_materials")
    op.drop_table("suppliers")
    op.drop_table("departments")
    op.drop_table("uploads")
    op.drop_table("users")
    op.drop_table("companies")
    op.execute("DROP TYPE IF EXISTS userrole")
    op.execute("DROP TYPE IF EXISTS uploadstatus")
    op.execute("DROP TYPE IF EXISTS productionstream")