"""Day 6 - purchases, production_batches, batch_department_steps, inventory_snapshots

Revision ID: 0002
Revises: 0001
Create Date: Day 6

Same caveat as 0001: written by hand against the models, not autogenerated
(no live Postgres in the dev environment this was built in). Verify with
`alembic revision --autogenerate -m "verify against 0002"` once you have a
real DB connection -- it should come back empty if this file is accurate.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "purchases",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("supplier_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("suppliers.id"), nullable=True),
        sa.Column("raw_material_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("raw_materials.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(12, 3), nullable=False),
        sa.Column("unit_price", sa.Numeric(12, 2), nullable=False),
        sa.Column("total_amount", sa.Numeric(14, 2), nullable=False),
        sa.Column("source_upload_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("uploads.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_purchases_company_id", "purchases", ["company_id"])
    op.create_index("ix_purchases_date", "purchases", ["date"])

    op.create_table(
        "production_batches",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("products.id"), nullable=True),
        sa.Column("batch_code", sa.String(50), nullable=True),
        # reuses the productionstream enum type created in 0001 -- do not recreate it
        sa.Column("stream", postgresql.ENUM("self_made", "cmt", "unspecified", name="productionstream", create_type=False),
                   server_default="unspecified"),
        sa.Column("material_input_quantity", sa.Numeric(12, 3), nullable=True),
        sa.Column("expected_output_quantity", sa.Numeric(12, 2), nullable=True),
        sa.Column("actual_output_quantity", sa.Numeric(12, 2), nullable=True),
        sa.Column("expected_waste", sa.Numeric(12, 3), nullable=True),
        sa.Column("actual_waste", sa.Numeric(12, 3), nullable=True),
        sa.Column("production_cost", sa.Numeric(14, 2), nullable=True),
        sa.Column("date_started", sa.Date(), nullable=True),
        sa.Column("date_completed", sa.Date(), nullable=True),
        sa.Column("source_upload_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("uploads.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_production_batches_company_id", "production_batches", ["company_id"])
    op.create_index("ix_production_batches_date_started", "production_batches", ["date_started"])

    op.create_table(
        "batch_department_steps",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("batch_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("production_batches.id"), nullable=False),
        sa.Column("department_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("departments.id"), nullable=True),
        sa.Column("sequence_order", sa.Integer(), nullable=False),
        sa.Column("quantity_in", sa.Numeric(12, 3), nullable=True),
        sa.Column("quantity_out", sa.Numeric(12, 3), nullable=True),
        sa.Column("expected_waste", sa.Numeric(12, 3), nullable=True),
        sa.Column("actual_waste", sa.Numeric(12, 3), nullable=True),
        sa.Column("cost_at_step", sa.Numeric(14, 2), nullable=True),
        sa.Column("date_started", sa.Date(), nullable=True),
        sa.Column("date_completed", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_batch_department_steps_company_id", "batch_department_steps", ["company_id"])
    op.create_index("ix_batch_department_steps_batch_id", "batch_department_steps", ["batch_id"])

    op.create_table(
        "inventory_snapshots",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("raw_material_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("raw_materials.id"), nullable=True),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("products.id"), nullable=True),
        sa.Column("inventory_type", sa.Enum("raw_material", "work_in_progress", "finished_goods", name="inventorytype"),
                   nullable=False),
        sa.Column("location", sa.Enum("warehouse", "shop", "wholesaler", name="inventorylocation"), nullable=True),
        sa.Column("location_detail", sa.String(255), nullable=True),
        sa.Column("quantity", sa.Numeric(14, 3), nullable=False),
        sa.Column("unit", sa.String(20), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("source_upload_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("uploads.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_inventory_snapshots_company_id", "inventory_snapshots", ["company_id"])
    op.create_index("ix_inventory_snapshots_snapshot_date", "inventory_snapshots", ["snapshot_date"])


def downgrade():
    op.drop_table("inventory_snapshots")
    op.execute("DROP TYPE IF EXISTS inventorylocation")
    op.execute("DROP TYPE IF EXISTS inventorytype")
    op.drop_table("batch_department_steps")
    op.drop_table("production_batches")
    op.drop_table("purchases")